CREATE TABLE PET_ENV_PROPERTY (
  ID             NUMBER       NOT NULL,
  PROPERTY_NAME  VARCHAR(255) NOT NULL,
  PROPERTY_VALUE VARCHAR(255),
  ENV            VARCHAR(255) NOT NULL,
  MACHINE        VARCHAR(255),
  CONSTRAINT PK_PET_ENV_PROP PRIMARY KEY (ID)
);