INSERT INTO PET_ENV_PROPERTY (ID, PROPERTY_NAME, PROPERTY_VALUE, ENV, MACHINE)
VALUES (1, 'url', 'www.google.com', 'DEV', NULL);

INSERT INTO PET_ENV_PROPERTY (ID, PROPERTY_NAME, PROPERTY_VALUE, ENV, MACHINE)
VALUES (2, 'url', 'www.kotaku.com', 'CORE', NULL);

INSERT INTO PET_ENV_PROPERTY (ID, PROPERTY_NAME, PROPERTY_VALUE, ENV, MACHINE)
VALUES (3, 'url', 'www.giantbomb.com', 'QA', NULL);

-- INSERT INTO PET_ENV_PROPERY (ID, PROPERTY_NAME, PROPERTY_VALUE, ENV, MACHINE)
-- VALUES (1, '', '', '', '');
--
-- INSERT INTO PET_ENV_PROPERY (ID, PROPERTY_NAME, PROPERTY_VALUE, ENV, MACHINE)
-- VALUES (1, '', '', '', '');